spring:
  data:
    mongodb:
      host: db
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false
  rabbitmq:
    host: codecharacter_rabbitmq
  sendgrid:
    api-key: your-api-key
    template-id: your-template-id
    sender-email: sender-email-id
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
            scope: user:email
environment:
  event-start-date: YYYY-MM-DDTHH:MM:SSZ
  reCaptcha-key: your-recaptcha-key
  no-of-tutorial-level: 0
  registration-time: "* * * * * *"
  game-start-time: "* * * * * *"
  tier-1-players: 20
  top-players: 5
  update-time: "*/20 * * * * *"

server:
  compression:
    enabled: true
  http2:
    enabled: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.4

debug: false

cors:
  enabled: true
  allowed-origin: http://localhost:3000

jwt:
  secret: 'example'

base-url: your-base-url
frontend-domain: localhost
